// Descrições dos CFOPs mais comuns (conforme Ajuste SINIEF 07/2005 e atualizações)
const CFOP_DESC = {
  // ENTRADAS (1xxx)
  '1101': 'Compra para industrialização ou produção rural',
  '1102': 'Compra para comercialização',
  '1111': 'Compra para industrialização de produção rural',
  '1113': 'Compra para comercialização, de produção rural',
  '1116': 'Compra de bem para ativo imobilizado',
  '1117': 'Compra de material para uso ou consumo',
  '1120': 'Compra de bem para ativo imobilizado de produção rural',
  '1121': 'Compra de material para uso ou consumo de produção rural',
  '1124': 'Industrialização efetuada por outra empresa',
  '1125': 'Comercialização efetuada por outra empresa',
  '1126': 'Outra entrada de mercadoria ou serviço sem destinatário',
  '1251': 'Industrialização efetuada por outra empresa',
  '1252': 'Comercialização efetuada por outra empresa',
  '1253': 'Industrialização efetuada por outra empresa de produção rural',
  '1254': 'Comercialização efetuada por outra empresa de produção rural',
  '1255': 'Industrialização efetuada por outra empresa de produção rural',
  '1256': 'Comercialização efetuada por outra empresa de produção rural',
  '1407': 'Compra de mercadoria para uso ou consumo',
  '1551': 'Compra de bem para ativo imobilizado',
  '1556': 'Compra de material para uso ou consumo',
  '1652': 'Compra de mercadoria recebida para venda em consignação',
  '1403': 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária',
  '1405': 'Compra para uso ou consumo em operação com mercadoria sujeita ao regime de substituição tributária',
  '1929': 'Outra entrada de mercadoria ou prestação de serviço não especificada',
  '1949': 'Outra entrada de mercadoria ou prestação de serviço não especificada',
  '2101': 'Compra para industrialização ou produção rural',
  '2102': 'Compra para comercialização',
  '2111': 'Compra para industrialização de produção rural',
  '2113': 'Compra para comercialização de produção rural',
  '2116': 'Compra de bem para o ativo imobilizado',
  '2117': 'Compra de material para uso ou consumo',
  '2120': 'Compra de bem para ativo imobilizado de produção rural',
  '2121': 'Compra de material para uso ou consumo de produção rural',
  '2124': 'Industrialização efetuada por outra empresa',
  '2125': 'Comercialização efetuada por outra empresa',
  '2252': 'Compra de mercadoria recebida para venda em consignação',
  '2251': 'Industrialização efetuada por outra empresa',
  '2551': 'Compra de bem para o ativo imobilizado',
  '2556': 'Compra de material para uso ou consumo',
  '2401': 'Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária',
  '2403': 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária',
  '2910': 'Entrada de bonificação, doação ou brinde',
  '1653': 'Compra de combustível ou lubrificante para comercialização',
  '2949': 'Outra entrada de mercadoria ou prestação de serviço não especificada',
  '1932': 'Prestação de serviço de transporte',
  '2932': 'Prestação de serviço de transporte',

  // SAÍDAS (5xxx e 6xxx)
  '5101': 'Venda de produção do estabelecimento',
  '5102': 'Venda de mercadoria adquirida ou recebida de terceiros',
  '5103': 'Venda de produção do estabelecimento, destinada à não industrialização ou produção rural',
  '5104': 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à não industrialização ou produção rural',
  '5105': 'Venda de produção do estabelecimento de produção rural',
  '5106': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '5115': 'Venda de bem do ativo imobilizado',
  '5116': 'Venda de material de uso ou consumo',
  '5117': 'Venda de produção do estabelecimento de produção rural',
  '5118': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '5403': 'Venda de mercadoria adquirida ou recebida de terceiros',
  '5405': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '5910': 'Venda de produção do estabelecimento de produção rural',
  '5911': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '5912': 'Venda de produção do estabelecimento de produção rural',
  '5913': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '5922': 'Venda de produção do estabelecimento de produção rural',
  '5923': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '6101': 'Venda de produção do estabelecimento',
  '6102': 'Venda de mercadoria adquirida ou recebida de terceiros',
  '6103': 'Venda de produção do estabelecimento, destinada à não industrialização ou produção rural',
  '6104': 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à não industrialização ou produção rural',
  '6105': 'Venda de produção do estabelecimento de produção rural',
  '6106': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '6115': 'Venda de bem do ativo imobilizado',
  '6116': 'Venda de material de uso ou consumo',
  '6117': 'Venda de produção do estabelecimento de produção rural',
  '6118': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '6403': 'Venda de mercadoria adquirida ou recebida de terceiros',
  '6405': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '6910': 'Venda de produção do estabelecimento de produção rural',
  '6911': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '6912': 'Venda de produção do estabelecimento de produção rural',
  '6913': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '6922': 'Venda de produção do estabelecimento de produção rural',
  '6923': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '5201': 'Devolução de compra para industrialização ou produção rural',
  '5949': 'Outra saída de mercadoria ou prestação de serviço não especificada',
  '5352': 'Prestação de serviço de transporte a estabelecimento industrial',
  '5353': 'Prestação de serviço de transporte a estabelecimento comercial',
  '6949': 'Outra saída de mercadoria ou prestação de serviço não especificada',
  '6352': 'Prestação de serviço de transporte a estabelecimento industrial',
  '6353': 'Prestação de serviço de transporte a estabelecimento comercial',
  '6201': 'Venda de produção do estabelecimento',
  '6202': 'Venda de mercadoria adquirida ou recebida de terceiros',
  '6203': 'Venda de produção do estabelecimento, destinada à não industrialização ou produção rural',
  '6204': 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à não industrialização ou produção rural',
  '6205': 'Venda de produção do estabelecimento de produção rural',
  '6206': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
  '6215': 'Venda de bem do ativo imobilizado',
  '6216': 'Venda de material de uso ou consumo',
  '6217': 'Venda de produção do estabelecimento de produção rural',
  '6218': 'Venda de mercadoria adquirida ou recebida de terceiros de produção rural',
};

export function getCfopDescricao(cfop) {
  if (!cfop) return '';
  const key = String(cfop).replace(/\D/g, '').padStart(4, '0');
  return CFOP_DESC[key] || '';
}

// Indica se o CFOP de saída representa efetivamente uma venda ou prestação
// de serviço (faturamento), excluindo devoluções de compra (52xx/62xx) e
// outras saídas não especificadas (X949).
export function isCfopVenda(cfop) {
  if (!cfop) return true;
  const key = String(cfop).replace(/\D/g, '').padStart(4, '0');
  if (key.startsWith('52') || key.startsWith('62')) return false;
  if (key === '5949' || key === '6949') return false;
  return true;
}